### PR TITLE
Grails Quartz plugin agnostic, other enhancements

### PR DESCRIPTION
**Pull request by robertoschwald**
- Works with Grails Quartz and Grails Schwartz
- Does not extend plugin factories, but registers a Quartz JobListener
- Added documentation sources (asciidoc)
- Travis CI support (you need to change the keys in .travis.yml)
- gh-docs support (you need to create a gh-pages branch)
- bintray deployment config

### CODE REVIEW

**Comment by zyro23** [comment]
@robertoschwald cool! looks like that supersedes #40 (#41), right?

**Comment by robertoschwald** [comment]
Yes.

**Comment by sdelamo** [comment]
Plus +1 for the merge of this pull-request. Looking forward to being able to use quartz-monitor Plugin with Schwartz too.

**Comment by zyro23** [comment]
any progress?

**Comment by robertoschwald** [comment]
Still not merged. Should I release a schwartz-monitor plugin?

**Comment by zyro23** [comment]
👍 for a release as a separate plugin. imho, this pr has been stale long enough.

**Comment by robertoschwald** [comment]
The grails-schwartz-plugin is released as own plugin since 2018. Closing this PR.
@jamescookie We will disconnect the https://github.com/symentis/grails-schwartz-monitor/tree/quartz-monitor-agnostic from your repo, soon. Hope this is ok with you. Your repo is credited in our README. If you want to have additional info in the credits, please contact me. Thanks.

**Pull request closed without merging**
